name: UI-CI

on:
  pull_request:
    paths: "packages/ui/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Typecheck
        run: npm run typecheck
      - name: Build package
        run: npm run build
